### ISSUE TITLE
Check base mode for matchers

### ISSUE THREAD

**Issue by udalrich** [mkcms/himp#1]
I use `jdee-mode` to edit java files, which is derived from `java-mode`.  If I do `M-x himp-mode` in a java file, I get an error message:

    himp-find-regions: No matchers for jdee-mode

There is a fairly simple workaround to copy the matchers for `java-mode`, but it would be better if it just checked for a match in the parent modes.

**Comment by mkcms** [comment]
Thanks. Added support for getting matchers from entries for parent modes.
